import sqlite3
import re
from datetime import datetime

SAMPLE_LOG = """
May 29 08:14:22 SERVER01 sshd: Failed password for admin from 192.168.1.105 port 22
May 29 08:14:25 SERVER01 sshd: Failed password for admin from 192.168.1.105 port 22
May 29 08:14:28 SERVER01 sshd: Failed password for root from 192.168.1.105 port 22
May 29 08:14:30 SERVER01 sshd: Failed password for admin from 192.168.1.105 port 22
May 29 09:31:05 SERVER01 sshd: Failed password for jsmith from 10.0.0.50 port 22
May 29 09:31:08 SERVER01 sshd: Failed password for jsmith from 10.0.0.50 port 22
May 29 10:15:00 SERVER01 sshd: Accepted password for tlee from 10.0.0.75 port 22
"""

THRESHOLD = 3

def parse_logs():
    failed_attempts = {}
    pattern = r'Failed password for (\w+) from ([\d.]+)'

    for line in SAMPLE_LOG.strip().split('\n'):
        match = re.search(pattern, line)
        if match:
            user = match.group(1)
            ip = match.group(2)
            if ip not in failed_attempts:
                failed_attempts[ip] = {'count': 0, 'users': set(), 'ip': ip}
            failed_attempts[ip]['count'] += 1
            failed_attempts[ip]['users'].add(user)

    conn = sqlite3.connect('dashboard.db')
    c = conn.cursor()

    for ip, data in failed_attempts.items():
        if data['count'] >= THRESHOLD:
            users_targeted = ', '.join(data['users'])
            message = f"Brute force detected: {data['count']} attempts on users [{users_targeted}] from {ip}"
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            c.execute("INSERT INTO alerts (type, message, severity, timestamp) VALUES (?,?,?,?)",
                      ('Log Parser Alert', message, 'High', timestamp))
            c.execute("INSERT INTO tickets (title, description, status, created) VALUES (?,?,?,?)",
                      (f'Brute Force - {ip}',
                       f'Auto-generated by log parser. {message}',
                       'Open', timestamp))
            print(f"[ALERT] {message}")

    conn.commit()
    conn.close()
    print("Log parsing complete.")

if __name__ == '__main__':
    parse_logs()